# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 04:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shared',
            old_name='wish',
            new_name='sharedwish',
        ),
    ]
